/**
 * - all tasks
 */
let tasks = [
    {
        assignet: [ "Greta Korn", "Peter Schleich" ],
        category: "Media",
        date: "2022-11-30",
        description: "make many of tests",
        dueDate: "2022-11-30",
        headline: "Test this Website",
        id: 0,
        initials: [ "GK", "PS" ],
        prio: "urgent",
        progress: "toDo",
        subTask: "Make Icon",
        tasksDone: 0,
        tasksOverall: 3,
        tasksPercent: 50,
        title: "Test this Website"
    },
    {
        assignet: [ "Peter Schleich" ],
        category: "Media",
        date: "2022-11-30",
        description: "test if responsive",
        dueDate: "2022-11-30",
        headline: "Test responsive",
        id: 1,
        initials: [ "PS" ],
        prio: "medium",
        progress: "inProgress",
        subTask: "Make Icon",
        tasksDone: 1,
        tasksOverall: 3,
        tasksPercent: 50,
        title: "Test Responsive"
    },
    {
        assignet: [ "Jörg Abratis", "Celine Holzinger", "Greta Korn",  "Pia Rose","Peter Schleich",  "Timm Schwarz"],
        category: "Marketing",
        date: "2022-11-30",
        description: "promote this Website",
        dueDate: "2022-11-30",
        headline: "Promotion",
        id: 2,
        initials: [ "JA", "CH", "GK", "PR", "PS", "TS" ],
        prio: "low",
        progress: "toDo",
        subTask: "Make Icon",
        tasksDone: 0,
        tasksOverall: 3,
        tasksPercent: 50,
        title: "Promotion"
    },
    {
        assignet: [ "Jörg Abratis", "Pia Rose","Peter Schleich",  "Timm Schwarz"],
        category: "Backoffice",
        date: "2022-11-30",
        description: "do something",
        dueDate: "2022-11-30",
        headline: "Something",
        id: 3,
        initials: [ "JA", "PR", "PS", "TS" ],
        prio: "low",
        progress: "awaitingFeedback",
        subTask: "Make Icon",
        tasksDone: 2,
        tasksOverall: 3,
        tasksPercent: 50,
        title: "Something"
    },
    {
        assignet: [ "Jörg Abratis", "Celine Holzinger", "Pia Rose", "Timm Schwarz"],
        category: "Design",
        date: "2022-11-30",
        description: "make everything beautiful",
        dueDate: "2022-11-30",
        headline: "Everything",
        id: 4,
        initials: [ "JA", "CH", "PR", "TS" ],
        prio: "low",
        progress: "done",
        subTask: "Make Icon",
        tasksDone: 3,
        tasksOverall: 3,
        tasksPercent: 50,
        title: "Everything"
    },
    {
        assignet: [ "Celine Holzinger", "Pia Rose","Peter Schleich",  "Timm Schwarz"],
        category: "Media",
        date: "2022-11-30",
        description: "try new colors",
        dueDate: "2022-11-30",
        headline: "Colors",
        id: 5,
        initials: [ "CH", "PR", "PS", "TS" ],
        prio: "low",
        progress: "done",
        subTask: "Make Icon",
        tasksDone: 3,
        tasksOverall: 3,
        tasksPercent: 50,
        title: "Color"
    },
];